name: soil_moisture_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^2.1.1+1
  syncfusion_flutter_charts: ^1.0.0-beta.4
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
  flutter_image: ^3.0.0
  provider: ^3.2.0
  shared_preferences: ^0.5.3+5
  google_fonts: ^0.1.1

  cupertino_icons: ^0.1.2
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/Soif_sk.png
   - assets/images/Soif_sk_dark.png
   - assets/images/plant.png
   - assets/images/plant_dark.png

  fonts:
    - family: Ocrb
      fonts:
        - asset: assets/fonts/Ocrb.ttf